version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_DATABASE: facturador
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: laravel
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

volumes:
    db_data:

networks:
    laravel:
